guide/essentials/template-syntax.md
edimitchel/docs-fr pull request #117
Opened 2022-09-12 15:33 UTC by edimitchel

- [x] Ancres anglaises ajoutées à chaque titre traduits
- [x] Liens pointant sur la page traduite par cette PR mis à jour
- [x] Lien de menu mis à jour

2022-09-13 16:27 UTC, unpseudocomplique commented on src/guide/essentials/template-syntax.md
> +[Les attributs booléens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) sont des attributs qui peuvent indiquer des valeurs vrai/faux par sa présence sur un élém
Plutôt cibler l'url fr : 
https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/disabled

2022-09-14 08:16 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
> +L'attribut `disabled` sera inclus si `boutonDésactivé` a une [valeur évaluée à vrai](https://developer.mozilla.org/en-US/docs/Glossary/Truthy). Il sera également inclus si la valeur est une chaîne vi
```suggestion
L'attribut `disabled` sera inclus si `boutonDésactivé` a une [valeur évaluée à vrai](https://developer.mozilla.org/fr/docs/Glossary/Truthy). Il sera également inclus si la valeur est une chaîne vide, en maintenant la cohérence avec `<button disabled="">`. Pour les [valeurs évaluées à faux](https://developer.mozilla.org/fr/docs/Glossary/Falsy), l'attribut sera omis.
```

2022-09-14 08:16 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
> +[Les attributs booléens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) sont des attributs qui peuvent indiquer des valeurs vrai/faux par sa présence sur un élém
```suggestion
[Les attributs booléens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) sont des attributs qui peuvent indiquer des valeurs vrai/faux par sa présence sur un élément. Par exemple, [`disabled`](https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/disabled) est l'un des attributs booléens les plus couramment utilisés.
```

2022-09-14 08:17 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
> +- Interpolations de texte à l'intérieur (moustaches)
```suggestion
- Dans une Interpolation de texte (moustaches)
```

2022-09-14 08:18 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
> +Chaque liaison ne peut contenir qu'**une seule expression**. Une expression est un morceau de code qui peut donner une valeur. Une simple vérification est de savoir s'il peut être utilisé après un `r
```suggestion
Chaque liaison ne peut contenir qu'**une seule expression**. Une expression est un morceau de code qui peut donner une valeur. Une simple vérification est de savoir si elle peut être utilisée après un `return`.
```

2022-09-14 08:22 UTC, edimitchel commented
Merci @unpseudocomplique, je t'invite à utiliser le bouton suggestion pour proposer un changement sur une ligne, ça simplifie la correction directement depuis github. 

![Capture d’écran 2022-09-14 à 10 20 39](https://user-images.githubusercontent.com/2922851/190101010-ad86b250-0ef5-453b-9f8f-98ae3ae948ad.png)

2022-10-09 15:06 UTC, unpseudocomplique approved these changes

2022-10-14 22:32 UTC, edimitchel commented
@marcbouvier, je veux bien une revue de ta part!

2022-10-24 08:01 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
>  Here, the `v-if` directive would remove / insert the `<p>` element based on the truthiness of the value of the expression `seen`.
```suggestion
```

2022-10-24 13:25 UTC, KeziahMoselle approved these changes

2022-10-24 20:37 UTC, unpseudocomplique requested changes

2022-10-24 20:37 UTC, unpseudocomplique commented on src/guide/essentials/template-syntax.md
> +<p v-if="vu">Maintenant, il est vu</p>
```suggestion
<p v-if="vu">Maintenant, tu me vois</p>
```

2022-10-24 20:37 UTC, unpseudocomplique commented on src/guide/essentials/template-syntax.md
> +Certaines directives peut prendre un "argument", distingé par un double-point après le nom de la directive. Par exemple, la directive `v-bind` est utilisé pour mettre à jour par réaction un attribute
```suggestion
Certaines directives peuvent prendre un "argument", distingé par un double-point après le nom de la directive. Par exemple, la directive `v-bind` est utilisé pour mettre à jour réactivement un attribut HTML :
```

2022-10-24 20:37 UTC, unpseudocomplique commented on src/guide/essentials/template-syntax.md
> +Si vous devez passer un argument dynamique complexe, il est probablement préférable d'utiliser une [TODO(fr)propriété calculée](./computed.html), que nous aborderons sous peu.
Ce serais pas mieux de laisser computed ici  puisque c'est le nom de la méthode de vue ?

2022-10-24 20:48 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
> +Si vous devez passer un argument dynamique complexe, il est probablement préférable d'utiliser une [TODO(fr)propriété calculée](./computed.html), que nous aborderons sous peu.
Je comprends la remarque, mais je pense qu'il est bon de le traduire, la page liée n'est pas l'API. La sémantique doit être comprise car computed suggère que c'est une valeur dérivée et calculée.

2022-10-24 20:55 UTC, merged