Conserve les ancres anglaises
edimitchel/docs-fr pull request #119
Opened 2022-10-11 16:55 UTC by KeziahMoselle

Cette PR ajoute les ancres anglaises sur les pages traduites

## Commencer

- [ ] Introduction
- [ ] Démarrage rapide

## Les essentiels

- [ ] Créer une application

#118

2022-10-13 09:59 UTC, edimitchel commented
Il manque la page SFC
https://vue-docs-fr.netlify.app/guide/scaling-up/sfc.html

2022-10-13 10:00 UTC, edimitchel requested changes
La page composants monofichier à transformer!

2022-10-17 12:29 UTC, KeziahMoselle commented
@edimitchel je souhaitais attendre une réponse sur le dépôt anglais par rapport aux ancres avant de continuer, mais visiblement pas de réponse. Je poursuis bientôt

2022-10-24 13:20 UTC, KeziahMoselle commented
J'ai reçu une réponse, ils vont rajouter les ancres sur le dépôt source, je clôture donc cette MR, on pourra rebase par la suite pour les récupérer.
https://github.com/vuejs/docs/issues/1998#issuecomment-1288316027

2022-10-24 13:20 UTC, closed without merging