Scaling up : Testing
edimitchel/docs-fr pull request #122
Opened 2022-10-12 12:40 UTC by marc-bouvier

#120 
Voir le glossaire proposé: #121

2022-10-14 18:52 UTC, edimitchel requested changes
Encore du travail, pense également à mettre à jour le menu dans config.ts

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +- **Unitaire **: Vérifie que les entrées d'une fonction, classe, ou composable donné produisent les sorties ou effets de bord attendus.
Déplace l'espace après les `**`

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +- **Unitaire **: Vérifie que les entrées d'une fonction, classe, ou composable donné produisent les sorties ou effets de bord attendus.
Pareil pour les deux suivants

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +Les tests de composant doivent détecter les problèmes liés aux props, aux événements, aux slots qu'il fournit, aux styles, aux classes, aux crochets de cycle de vie de votre composant, etc.
Pas fan de crochet de cycle de vie, je dirai simplement `aux differents cycles de vie de votre composant`

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +Les principales différences entre Vitest et les runners basés sur un navigateur sont la vitesse et le contexte d'exécution. En bref, les runners basés sur un navigateur, comme Cypress, peuvent détect
la page de comparaison de Vitest ? (l minuscule)

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +  Dans l'ensemble, nous pensons que Cypress fournit la solution E2E la plus complète avec des fonctionnalités telles qu'une interface graphique informative, une excellente déboguabilité, des assertio
resistance aux flocons?
Difficile à traduire celui-là.
j'ai trouvé résistance à l'écaillement qui serait peut-être plus parlant?

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
>  ```
Manque la traduction de la config ci-dessus

2022-10-14 18:52 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +Lorsqu'il est question de tester des composables, nous pouvons diviser en deux catégories : les composables qui ne dépendent pas d'une instance de composant hôte et ceux qui en dépendent.
Manque un paragraphe ci-dessous

2022-10-14 19:01 UTC, marc-bouvier commented on src/guide/scaling-up/testing.md
> +Les tests de composant doivent détecter les problèmes liés aux props, aux événements, aux slots qu'il fournit, aux styles, aux classes, aux crochets de cycle de vie de votre composant, etc.
Ah oui, je mets hook normalement

2022-10-15 14:25 UTC, marc-bouvier commented on src/guide/scaling-up/testing.md
> +   Les tests "Boîte blanche" ont "conscience" des détails d'implémentation et des dépendances d'un composant. Ils They are focused on **isolating** the component under test. These tests will usually
Voilà qui est fait

2022-10-15 14:43 UTC, marc-bouvier commented on src/guide/scaling-up/testing.md
> +- **Unitaire **: Vérifie que les entrées d'une fonction, classe, ou composable donné produisent les sorties ou effets de bord attendus.
Done

2022-10-15 14:44 UTC, marc-bouvier commented on src/guide/scaling-up/testing.md
> +Les tests de composant doivent détecter les problèmes liés aux props, aux événements, aux slots qu'il fournit, aux styles, aux classes, aux crochets de cycle de vie de votre composant, etc.
Done

2022-10-15 14:47 UTC, marc-bouvier commented on src/guide/scaling-up/testing.md
> +Les principales différences entre Vitest et les runners basés sur un navigateur sont la vitesse et le contexte d'exécution. En bref, les runners basés sur un navigateur, comme Cypress, peuvent détect
done

2022-10-15 15:02 UTC, marc-bouvier commented on src/guide/scaling-up/testing.md
> +  Dans l'ensemble, nous pensons que Cypress fournit la solution E2E la plus complète avec des fonctionnalités telles qu'une interface graphique informative, une excellente déboguabilité, des assertio
Peut-être :
- résistance à l'instabilité des tests
- résistance à la "test flakiness"

Je pense qu'il vaut mieux rester sur le concept de "flaky", on n'utilise pas vraiment d'équivalent en français. Et si c'est le cas, il n'y a pas de consensus et de Si quelqu'un cherche "flaky" sur internet il trouvera plus de ressources sur le sujet (même en français).

- https://docs.microsoft.com/fr-fr/azure/devops/pipelines/test/flaky-test-management
- https://blog.octo.com/la-pyramide-des-tests-par-la-pratique-1-5/
- https://eh-bien-testez-maintenant.github.io/2018/09/02/test-automatique-flakiness/

2022-10-15 15:08 UTC, marc-bouvier commented
Je n'ai pas trouvé de `config.ts` de quel fichier fais-tu référence?

2022-10-15 18:26 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +  Dans l'ensemble, nous pensons que Cypress fournit la solution E2E la plus complète avec des fonctionnalités telles qu'une interface graphique informative, une excellente déboguabilité, des assertio
ok pour flaky

2022-10-15 18:26 UTC, edimitchel commented
> Je n'ai pas trouvé de `config.ts` de quel fichier fais-tu référence?

Pourtant: https://github.com/edimitchel/docs-fr/blob/main/.vitepress/config.ts

2022-10-15 18:29 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +   Les tests "Boîte blanche" ont "conscience" des détails d'implémentation et des dépendances d'un composant. Ils se concentrent sur l'isolation du composant testé. Ces tests impliquent en général de
```suggestion
   Les tests "Boîte blanche" ont "conscience" des détails d'implémentation et des dépendances d'un composant. Ils se concentrent sur l'**isolation** du composant testé. Ces tests impliquent en général de simuler certains sinon tous les enfants de votre composant ainsi que d'initialiser l'état de plugins et dépendances (ex. Pinia). 
```

2022-10-15 18:30 UTC, edimitchel requested changes

2022-10-15 18:30 UTC, edimitchel commented on src/guide/scaling-up/testing.md
> +   Les tests "Boîte blanche" ont "conscience" des détails d'implémentation et des dépendances d'un composant. Ils se concentrent sur l'isolation du composant testé. Ces tests impliquent en général de
```suggestion
   Les tests "Boîte blanche" ont "conscience" des détails d'implémentation et des dépendances d'un composant. Ils se concentrent sur l'**isolation** du composant testé. Ces tests impliquent en général de simuler certains sinon tous les enfants de votre composant ainsi que d'initialiser l'état de plugins et dépendances (ex. Pinia). 
```

2022-10-24 07:42 UTC, marc-bouvier commented
> > Je n'ai pas trouvé de `config.ts` de quel fichier fais-tu référence?
> 
> Pourtant: https://github.com/edimitchel/docs-fr/blob/main/.vitepress/config.ts

J'ai capté entre temps :)

2022-10-24 07:44 UTC, edimitchel requested changes

2022-10-24 07:47 UTC, edimitchel approved these changes

2022-10-24 07:47 UTC, merged

2022-10-24 07:47 UTC, edimitchel commented
Merci beaucoup!