feat: translate i18n texts
edimitchel/docs-fr pull request #124
Opened 2022-10-15 21:07 UTC by edimitchel

Closes #123

2022-10-16 22:36 UTC, kissu requested changes

2022-10-16 22:36 UTC, kissu commented on .vitepress/config.ts
> +          },
Setting différent pour Prettier (line width) ici?

2022-10-16 22:36 UTC, kissu commented on .vitepress/config.ts
> +          }
Same ici, il y a une différence ici?

2022-10-16 22:36 UTC, kissu commented on .vitepress/config.ts
> +    after: 'a chargé'
J'ai pas trop le contexte de ce texte là, c'est quelle partie du site? (faudrait que je le fork et check en local surtout)

2022-10-16 22:36 UTC, kissu commented on .vitepress/config.ts
> +  ariaDarkMode: 'Mode foncé',
```suggestion
  ariaDarkMode: 'Mode sombre',
```

2022-10-16 22:36 UTC, kissu commented on .vitepress/config.ts
> +  ariaSidebarNav: 'Navigation de barre latérale'
```suggestion
  ariaSidebarNav: 'Barre de navigation latérale'
```

2022-10-16 22:36 UTC, kissu commented on .vitepress/config.ts
> +  ariaMobileNav: 'Navigation pour mobile',
```suggestion
  ariaMobileNav: 'Navigation mobile',
```

2022-10-16 22:41 UTC, edimitchel commented on .vitepress/config.ts
> +          },
Curieux, je ne sais pas, en tout cas, ça ne bouge plus là

2022-10-16 22:43 UTC, edimitchel commented on .vitepress/config.ts
> +    after: 'a chargé'
C'est pour le screen reader, ça écrit le nom de page avec le before avant et le after après. La version anglaise utilise la même tournure sans le before
"Guide - créer une application a chargé"

2022-10-17 12:28 UTC, KeziahMoselle approved these changes

2022-10-19 23:12 UTC, merged